### ISSUE TITLE
Add a wildcard for subdomains

### ISSUE THREAD

**Issue by meliurwen** [arosh/ublacklist-github-translation#1]
## Description

Some sites (for example `gitmemory.com`) use the domain and a subdomain like `www` interchangeably, this leads to both appear on google search results.

A solution could be to put a wildcard in case of a (or multiple) subdomain, like this:

```diff
- *://www.gitmemory.com/*
+ *://*.gitmemory.com/*
```
## How to reproduce

Search on google: `site:gitmemory.com` and `site:www.gitmemory.com`

**Comment by arosh** [comment]
@meliurwen 
Resolved by #2. Thanks.
